### ISSUE TITLE
SQL Schema is returning error on mariadb

### ISSUE THREAD

**Issue by Eliaxie** [PoliNetworkOrg/PoliFemoBackend#85] opened 2023-01-13 23:19 UTC
- on [this](https://github.com/PoliNetworkOrg/PoliFemoBackend/blob/b88f4d83feefdafef952235a4289a97cde2e516c/Other/DB/DBPolifemo.SQL#L138) error: ```/* Errore SQL (1064): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 5 */
/* Righe interessate: 0  Righe trovate: 0  Avvisi: 0  Durata di 0 di 10 query: 0,000 sec. */```
- and [this](https://github.com/PoliNetworkOrg/PoliFemoBackend/blob/b88f4d83feefdafef952235a4289a97cde2e516c/Other/DB/DBPolifemo.SQL#L150) query error: ```/* Errore SQL (1221): Incorrect usage of OR REPLACE and IF NOT EXISTS */```

**Comment by francescolf** [comment] 2023-01-15 18:16
Cannot reproduce the first error on MariaDB 10.3.37

**Comment by Eliaxie** [comment] 2023-01-15 18:19
The mariadb version in use can be found here alongside the full specs of the pod https://github.com/PoliNetworkOrg/polinetwork-cd/blob/main/mariadb/mariadb.yaml

**Comment by francescolf** [comment] 2023-01-18 18:15
Fixed in [964a599](https://github.com/PoliNetworkOrg/PoliFemoBackend/commit/964a5997831cefe382dce8fa18a44c4ca71eec53)

**Closed as completed by francescolf** 2023-01-18 18:15 UTC
